name: 'Build linux'
description: 'Build cutter in a docker image'
inputs: 
  system-deps:
    description: 'Use system libraries instead of cutter-deps'
    required: true
  image:
    description: 'Docker image'
    required: true
  qt-major:
    description: 'Qt major version'
    required: true
runs:
  using: 'docker'
  image: ${{ inputs.image }}
  entrypoint: './.github/actions/build-linux-old/entrypoint.sh'
  args: 
    - ${{ inputs.system-deps }}
    - ${{ inputs.system-image }}
    - ${{ inputs.qt-major }}
